### ISSUE TITLE
getOTPValidationUrl is not a method of serviceProviderInterface

### ISSUE THREAD

**Issue by andela-tolotin** [korotovsky/SingleSignOnIdentityProviderBundle#12]
Hi @korotovsky, Please can you help me explain why I'm  getting this error.
<img width="1280" alt="screen shot 2016-08-22 at 12 20 00 pm" src="https://cloud.githubusercontent.com/assets/14159435/17853155/ccd8610a-6862-11e6-9192-db0a31671f52.png">

getOTPValidationUrl is not a method in a class that extends `Krtv\Bundle\SingleSignOnIdentityProviderBundle\Manager\ServiceProviderInterface`

**Comment by dmilanaraujo** [comment]
The getOTPValidationUrl method exists. Please a solution because they do not really know how to generate the _target_path.
