### ISSUE TITLE
OTP Failure

### ISSUE THREAD

**Issue by mediafigaro** [korotovsky/SingleSignOnIdentityProviderBundle#19]
Hello, I still do have an OTP failure though I have the same secret on IDP and SP. Process : 

sp redirects to idp/login?_otp_failure=1&_otp_failure_time=1501579809.9692&_hash=fueAmfqYDQnqYV0PU%2F7onZL6jga07u2YCbAOarRIbJE%3D 

(logged, session registred)

OTP validation REST request seems to be ok as into the database I can see the password + the USED status.

Do you have an idea of what would go wrong here ?

Thanks.

**Comment by korotovsky** [comment]
It's absolutely impossible to help without any kind of code, configuration and so on... The only I can say is this redirect generates on SP side, so you have to debug security layer there

**Comment by mediafigaro** [comment]
hello, thanks I re tried the installation, he is the first step to something functional : https://github.com/mediafigaro/sso_idp + https://github.com/mediafigaro/sso_sp for now http://sso_sp.com
redirects to 👍 
http://sso_idp.com/sso/login/?_failure_path=http%3A%2F%2Fsso_idp.com%2Flogin%3F_target_path%3Dhttp%253A%252F%252Fsso_sp.com%252F%253F_hash%253DttPs2J9pbQNgpfUYnxo3Ck5gA6%25252FQALXI55VpPifB3rs%25253D&_target_path=http%3A%2F%2Fsso_sp.com%2Fotp%2Fvalidate%2F%3F_target_path%3Dhttp%253A%252F%252Fsso_sp.com%252F%253F_hash%253DttPs2J9pbQNgpfUYnxo3Ck5gA6%25252FQALXI55VpPifB3rs%25253D&service=consumer1&_hash=MeNs3iqXbuI72lc6sxYXmbz9zFX3NvJMK%2BocvFfwkdA%3D
= 400 Bad Request

so if you have some time you could have a quick look to the configuration. thanks

**Comment by korotovsky** [comment]
I'll try on this week

**Comment by mediafigaro** [comment]
hello, in case of: https://github.com/mediafigaro/sso-idp & https://github.com/mediafigaro/sso-sp
