### ISSUE TITLE
Using alongside FOSUserBundle - No route found for "GET /login_check": Method Not Allowed (Allow: POST)

### ISSUE THREAD

**Issue by cprichards** [korotovsky/SingleSignOnIdentityProviderBundle#22]
I've managed to nearly get this working but when I'm logging into the IdP I'm getting the error 

> No route found for "GET /login_check": Method Not Allowed (Allow: POST)

This is my security config and I'm not sure where to go next as there seems to be some kind of conflict. Is there any way to get this working with the `fos_userbundle`?

`security:
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
                login_path: /
                success_handler: user_listener
                use_referer: true
            logout:
                success_handler: logout_listener
            anonymous:    true`

**Comment by korotovsky** [comment]
Check your routing. You defined that `/login_check` is allowed only as a POST request but seems to be IdP  redirects you to this URL as a GET request (regular redirect)

**Comment by korotovsky** [comment]
`_otp_failure` parameter on IdP means that API request from SP to IdP had failed 99%. Try to debug SP security listeners, include from the SP bundle. 

Also in the Google Chrome Dev Tools you can check "Preserve Logs" to see the exact chain of redirects.

**Comment by cprichards** [comment]
Thanks. I'll take a look and get back to you either way.

**Comment by cprichards** [comment]
After catching $otp and $token->getCredentials() in the authenticate method and getting `null` and `duFVKjsQp6Mw11dCFB4ZP69KQaiXZBWyXnGLFuYaWVwtFf6+M3zd6myeumxsk7lRGiIDnoSaV7m08MxuCzluVA==` respectively, I started looking in my logs and spotted that I'm getting a curl error. First, it was related to the local domain not being registered in my host file. Now it's complaining about the Self Signed certificate. 

`app.ERROR: cURL error 60: SSL certificate problem: self signed certificate (see http://curl.haxx.se/libcurl/c/libcurl-errors.html) [] []`

Just updating my curl and ca-certificates to see if that helps. Thanks for your help.

**Comment by korotovsky** [comment]
@cprichards BTW, if you got redirected to /login by the SP, it's still incorrect in your case even if you would fix the SSL certificate, imagine the real case when OTP would fail. So you need to make a proper configuration of your SP https://github.com/korotovsky/SingleSignOnServiceProviderBundle#step-5-modify-security-settings check `sso_failure_path` parameter.
